In [ ]:
import pandas as pd
import torch
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader
from dataclasses import dataclass
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from types import SimpleNamespace
from tqdm import tqdm
import itertools

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
class Instance:
    def __init__(self, text, label):
        self.text = text.split(' ')
        self.label = label

In [ ]:
class Vocab:
    def __init__(self, frequency, max_size, min_freq):
      self.stoi = {}
      self.itos = {}

      frequency = sorted(frequency.items(), key=lambda x: x[1], reverse=True)
      for i, (w, f) in enumerate(frequency):
        if f >= min_freq and (len(self.stoi) < max_size or max_size == -1):
          self.stoi[w] = i
          self.itos[i] = w
        else:
          break

    def __len__(self):
      return len(self.stoi)

    def encode(self, tokens):
      if isinstance(tokens, str):
        return torch.tensor(self.stoi.get(tokens, self.stoi.get('<UNK>', 0)))
      return torch.tensor([self.stoi.get(token, self.stoi.get('<UNK>', 0)) for token in tokens])

In [ ]:
def calc_frequencies(data):
  word_counter = {}
  label_counter = {}

  for d in data:
    for word in d.text:
      word_counter[word] = word_counter.get(word, 0) + 1
    label_counter[d.label] = label_counter.get(d.label, 0) + 1
  return word_counter, label_counter

In [ ]:
class NPLDataset(torch.utils.data.Dataset):
    def __init__(self, path, split="train", max_size=-1, min_freq=0):
        self.data = []
        csv = pd.read_csv(path, sep=', ', header=None)

        for _, row in csv.iterrows():
            self.data.append(Instance(row[0], row[1]))

        if split == "train":
          self.frequency = calc_frequencies(self.data)
          self.frequency[0]['<PAD>'] = float('inf')
          self.frequency[0]['<UNK>'] = float('inf')
          self.text_vocab = Vocab(self.frequency[0], max_size, min_freq)
          self.label_vocab = Vocab(self.frequency[1], -1, 1)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.text_vocab.encode(self.data[index].text), self.label_vocab.encode(self.data[index].label)

In [ ]:
d = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_train_raw.csv')
d.data[3].text

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


['yet', 'the', 'act', 'is', 'still', 'charming', 'here']

In [ ]:
class Embedding(nn.Module):
  def __init__(self, vocab, path, embedding_dim=300):
    super(Embedding, self).__init__()
    self.embedding = nn.Embedding(len(vocab), embedding_dim, padding_idx=vocab.stoi['<PAD>'])

    embed = {}
    if path is not None:
      with open(path) as f:
        for i in f:
          word, vector = i.split(' ', 1)
          embed[word] = torch.tensor([float(x) for x in vector.split()])

    for i, word in vocab.itos.items():
      if word == '<PAD>':
        self.embedding.weight.data[i] = torch.zeros(embedding_dim)
      elif word in embed:
        self.embedding.weight.data[i] = embed[word]

    self.embedding.freeze = path is not None

  def forward(self, x):
    return self.embedding(x)

In [ ]:
def pad_collate_fn(batch, pad_index=0):
    texts, labels = zip(*batch)
    lengths = torch.tensor([len(text) for text in texts])

    max_length = lengths.max()
    padded = torch.stack([F.pad(text, (0, max_length - len(text)), value=pad_index) for text in texts])
    return padded, torch.tensor(labels), lengths

In [ ]:
train_dataldr = DataLoader(dataset=d, batch_size=2, shuffle=False, collate_fn=pad_collate_fn)
texts, labels, lengths = next(iter(train_dataldr))
print(f"Texts: {texts}")
print(f"Labels: {labels}")
print(f"Lengths: {lengths}")

Texts: tensor([[   2,  554,    7, 2872,    6,   22,    2, 2873, 1236,    8,   96, 4800,
            4,   10,   72,    8,  242,    6,   75,    3, 3576,   56, 3577,   34,
         2022, 2874, 7123, 3578, 7124,   42,  779, 7125,    0,    0],
        [   2, 2875, 2023, 4801,    5,    2, 3579,    5,    2, 2876, 4802,    7,
           40,  829,   10,    3, 4803,    5,  627,   62,   27, 2877, 2024, 4804,
          962,  715,    8, 7126,  555,    5, 7127, 4805,    8, 7128]])
Labels: tensor([0, 0])
Lengths: tensor([32, 34])


In [ ]:
class Model(nn.Module):
  def __init__(self, embedding, embedding_dim=300):
    super().__init__()
    self.embedding = embedding
    self.fc1 = nn.Linear(embedding_dim, 150)
    self.fc2 = nn.Linear(150, 150)
    self.fc3 = nn.Linear(150, 1)

  def forward(self, x):
    emb = self.embedding(x)
    pool = F.avg_pool1d(emb.permute(0, 2, 1), emb.shape[1]).squeeze(2)
    x = F.relu(self.fc1(pool))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    x = x.squeeze(1)
    return x

In [ ]:
def train(model, data, optimizer, criterion, args):
  total_loss = 0
  model.train()

  with tqdm(total=len(data)) as pbar:
    pbar.set_description("Training")
    for batch_num, batch in enumerate(data):
      x, y, _ = batch
      x, y = x.to(args.device), y.to(args.device).float()

      optimizer.zero_grad()
      logits = model(x)
      loss = criterion(logits, y.float())
      loss.backward()
      torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
      optimizer.step()
      total_loss = total_loss + loss.item()
      pbar.set_postfix(loss=loss.item())
      pbar.update(1)
  return total_loss / len(data)


def evaluate(model, data, criterion, args):
  total_loss = 0
  all_labels = []
  all_preds = []

  model.eval()

  with torch.no_grad():
    for batch_num, batch in enumerate(data):
      x, y, _ = batch
      x, y = x.to(args.device), y.to(args.device).float()
      logits = model(x)
      loss = criterion(logits, y.float())
      total_loss = total_loss + loss.item()

      predictions = torch.sigmoid(logits) >= 0.5
      all_labels.extend(predictions.cpu().numpy())
      all_preds.extend(y.cpu().numpy())

  avg_loss = total_loss / len(data)
  accuracy = accuracy_score(all_labels, all_preds)
  f1 = f1_score(all_labels, all_preds)
  cm = confusion_matrix(all_labels, all_preds)

  print(f"Loss: {avg_loss}")
  print(f"Accuracy: {accuracy}")
  print(f"F1: {f1}")
  print(f"Confusion Matrix: \n{cm}")

  return avg_loss, accuracy, f1, cm

In [ ]:
def main(args):
  seed = args.seed

  train_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_train_raw.csv')
  valid_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_valid_raw.csv')
  test_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_test_raw.csv')
  vocab = train_dataset.text_vocab
  valid_dataset.text_vocab = vocab
  test_dataset.text_vocab = vocab
  valid_dataset.label_vocab = train_dataset.label_vocab
  test_dataset.label_vocab = train_dataset.label_vocab

  train_dataloader = DataLoader(dataset=train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=pad_collate_fn)
  valid_dataloader = DataLoader(dataset=valid_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)
  test_dataloader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

  embedding = Embedding(vocab, '/content/drive/MyDrive/Colab Notebooks/sst_glove_6b_300d.txt', args.embedding_dim)
  np.random.seed(seed)
  torch.manual_seed(seed)
  model = Model(embedding, embedding_dim=args.embedding_dim)
  model.to(args.device)

  criterion = nn.BCEWithLogitsLoss()
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

  for epoch in range(args.epochs):
    print(f"Epoch: {epoch+1}")
    train(model, train_dataloader, optimizer, criterion, args)
    evaluate(model, valid_dataloader, criterion, args)

  print("Testing model")
  evaluate(model, test_dataloader, criterion, args)

In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "embedding_dim": 300,
    "epochs": 5,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 1.0
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 81.05it/s, loss=0.709] 


Loss: 0.5737520377886923
Accuracy: 0.7534321801208127
F1: 0.7369654364381957
Confusion Matrix: 
[[743 283]
 [166 629]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 103.97it/s, loss=0.495]


Loss: 0.45032397592276857
Accuracy: 0.8045030203185063
F1: 0.8011173184357542
Confusion Matrix: 
[[748 195]
 [161 717]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 146.14it/s, loss=0.382]


Loss: 0.4736872323249516
Accuracy: 0.7830862163646348
F1: 0.7472808701215611
Confusion Matrix: 
[[842 328]
 [ 67 584]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:04<00:00, 170.28it/s, loss=0.48]


Loss: 0.417522920589698
Accuracy: 0.814936847885777
F1: 0.8137092316196793
Confusion Matrix: 
[[748 176]
 [161 736]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:04<00:00, 163.08it/s, loss=0.332]


Loss: 0.42897985222046836
Accuracy: 0.8094453596924767
F1: 0.7993059572006941
Confusion Matrix: 
[[783 221]
 [126 691]]
Testing model
Loss: 0.4651187466723578
Accuracy: 0.7970183486238532
F1: 0.7849331713244229
Confusion Matrix: 
[[372 105]
 [ 72 323]]


In [ ]:
class RNN(nn.Module):
  def __init__(self, type_, embedding, input_size, hidden_size, num_layers, bidirectional, dropout, batch_first=True):
    super(RNN, self).__init__()
    self.embedding = embedding
    self.input_size = input_size
    self.hidden_size = hidden_size
    self.bidirectiona = bidirectional

    if type_ == 'LSTM':
      self.rnn = nn.LSTM(input_size, hidden_size, num_layers, batch_first=batch_first, bidirectional=bidirectional, dropout=dropout)
    elif type_ == 'GRU':
      self.rnn = nn.GRU(input_size, hidden_size, num_layers, batch_first=batch_first, bidirectional=bidirectional, dropout=dropout)
    elif type_ == 'RNN':
      self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=batch_first, bidirectional=bidirectional, dropout=dropout)

    fc_input = hidden_size * 2 if bidirectional else hidden_size

    self.fc1 = nn.Linear(fc_input, hidden_size)
    self.fc2 = nn.Linear(hidden_size, 1)

  def forward(self, x):
    emb = self.embedding(x)
    hidden, _ = self.rnn(emb)
    hidden = hidden[:, -1, :]

    x = self.fc1(hidden)
    x = F.relu(x)
    x = self.fc2(x).squeeze(1)
    return x

In [ ]:
def main(args):
  seed = args.seed

  model_type = ['LSTM', 'GRU', 'RNN']

  train_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_train_raw.csv')
  valid_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_valid_raw.csv')
  test_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_test_raw.csv')
  vocab = train_dataset.text_vocab
  valid_dataset.text_vocab = vocab
  test_dataset.text_vocab = vocab
  valid_dataset.label_vocab = train_dataset.label_vocab
  test_dataset.label_vocab = train_dataset.label_vocab

  train_dataloader = DataLoader(dataset=train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=pad_collate_fn)
  valid_dataloader = DataLoader(dataset=valid_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)
  test_dataloader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

  embedding = Embedding(vocab, '/content/drive/MyDrive/Colab Notebooks/sst_glove_6b_300d.txt', args.embedding_dim)
  np.random.seed(seed)
  torch.manual_seed(seed)

  for type_ in model_type:
    print(f"Model type: {type_}")
    model = RNN(type_, embedding=embedding, input_size=args.embedding_dim, hidden_size=args.hidden_size, num_layers=args.num_layers, bidirectional=args.bidirectional, dropout=args.dropout)
    model.to(args.device)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    for epoch in range(args.epochs):
      print(f"Epoch: {epoch+1}")
      train(model, train_dataloader, optimizer, criterion, args)
      evaluate(model, valid_dataloader, criterion, args)

    print("Testing model")
    evaluate(model, test_dataloader, criterion, args)

In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 150,
    "num_layers": 3,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 0.25,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 99.36it/s, loss=0.316]


Loss: 0.5935396523329249
Accuracy: 0.7457440966501923
F1: 0.7026332691072575
Confusion Matrix: 
[[811 365]
 [ 98 547]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 99.36it/s, loss=0.348] 


Loss: 0.4378935464641504
Accuracy: 0.7973640856672158
F1: 0.8091050181065701
Confusion Matrix: 
[[670 130]
 [239 782]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 98.94it/s, loss=0.718]


Loss: 0.5964657998921579
Accuracy: 0.8110928061504667
F1: 0.8130434782608695
Confusion Matrix: 
[[729 164]
 [180 748]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:07<00:00, 93.32it/s, loss=0.0918] 


Loss: 0.4549516985813777
Accuracy: 0.8088962108731467
F1: 0.8143009605122732
Confusion Matrix: 
[[710 149]
 [199 763]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:07<00:00, 93.46it/s, loss=0.198] 


Loss: 0.6009205781054079
Accuracy: 0.8127402526084568
F1: 0.8085345311622684
Confusion Matrix: 
[[760 192]
 [149 720]]
Testing model
Loss: 0.6233359373041562
Accuracy: 0.823394495412844
F1: 0.8192488262910798
Confusion Matrix: 
[[369  79]
 [ 75 349]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 107.90it/s, loss=0.675]


Loss: 0.44521751816858324
Accuracy: 0.8116419549697969
F1: 0.8225556130367304
Confusion Matrix: 
[[683 117]
 [226 795]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 95.14it/s, loss=0.635] 


Loss: 0.6558896352847418
Accuracy: 0.7836353651839648
F1: 0.758578431372549
Confusion Matrix: 
[[808 293]
 [101 619]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 107.95it/s, loss=0.0267]


Loss: 0.964513341585795
Accuracy: 0.7578253706754531
F1: 0.7046215673141326
Confusion Matrix: 
[[854 386]
 [ 55 526]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:07<00:00, 96.71it/s, loss=0.014] 


Loss: 0.9821697531039255
Accuracy: 0.7759472817133443
F1: 0.7475247524752475
Confusion Matrix: 
[[809 308]
 [100 604]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:06<00:00, 109.51it/s, loss=0.00335]


Loss: 1.1080411981072342
Accuracy: 0.7742998352553542
F1: 0.745195288282703
Confusion Matrix: 
[[809 311]
 [100 601]]
Testing model
Loss: 1.1347071123974664
Accuracy: 0.7798165137614679
F1: 0.7493472584856397
Confusion Matrix: 
[[393 141]
 [ 51 287]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 123.09it/s, loss=0.274]


Loss: 0.5334115838795378
Accuracy: 0.7825370675453048
F1: 0.7585365853658537
Confusion Matrix: 
[[803 290]
 [106 622]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:04<00:00, 144.22it/s, loss=0.449]


Loss: 0.7921167863042731
Accuracy: 0.7841845140032949
F1: 0.764247150569886
Confusion Matrix: 
[[791 275]
 [118 637]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 143.79it/s, loss=0.014]


Loss: 0.8877397707679815
Accuracy: 0.7957166392092258
F1: 0.7995689655172413
Confusion Matrix: 
[[707 170]
 [202 742]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 131.70it/s, loss=0.0221]


Loss: 1.0462715861044432
Accuracy: 0.7830862163646348
F1: 0.7587049480757483
Confusion Matrix: 
[[805 291]
 [104 621]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:04<00:00, 146.24it/s, loss=1.11]


Loss: 1.0092716674532807
Accuracy: 0.8017572762218561
F1: 0.7904817179338364
Confusion Matrix: 
[[779 231]
 [130 681]]
Testing model
Loss: 1.0529521267328943
Accuracy: 0.7935779816513762
F1: 0.7777777777777778
Confusion Matrix: 
[[377 113]
 [ 67 315]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 50,
    "num_layers": 3,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 0.25,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 123.43it/s, loss=0.685]


Loss: 0.6939139292951215
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 125.62it/s, loss=0.646]


Loss: 0.5042564814027987
Accuracy: 0.7940691927512356
F1: 0.7863247863247863
Confusion Matrix: 
[[756 222]
 [153 690]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:05<00:00, 136.59it/s, loss=0.46]


Loss: 0.4664101807171838
Accuracy: 0.8056013179571664
F1: 0.8088552915766739
Confusion Matrix: 
[[718 163]
 [191 749]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 117.44it/s, loss=0.464]


Loss: 0.5100492045544741
Accuracy: 0.8050521691378364
F1: 0.7903130537507383
Confusion Matrix: 
[[797 243]
 [112 669]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:05<00:00, 133.87it/s, loss=0.163]


Loss: 0.5152940033820638
Accuracy: 0.8165842943437671
F1: 0.8140311804008908
Confusion Matrix: 
[[756 181]
 [153 731]]
Testing model
Loss: 0.5658269269125802
Accuracy: 0.8027522935779816
F1: 0.7981220657276995
Confusion Matrix: 
[[360  88]
 [ 84 340]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 126.96it/s, loss=0.675]


Loss: 0.6923924119848954
Accuracy: 0.5041186161449753
F1: 0.060353798126951096
Confusion Matrix: 
[[889 883]
 [ 20  29]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 131.85it/s, loss=0.0983]


Loss: 0.535192398648513
Accuracy: 0.771554091158704
F1: 0.7913741223671013
Confusion Matrix: 
[[616 123]
 [293 789]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 138.58it/s, loss=0.034]


Loss: 0.7072797004590955
Accuracy: 0.7506864360241625
F1: 0.7872539831302718
Confusion Matrix: 
[[527  72]
 [382 840]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 121.29it/s, loss=0.869]


Loss: 0.8444765340863613
Accuracy: 0.7534321801208127
F1: 0.7869008068343617
Confusion Matrix: 
[[543  83]
 [366 829]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:05<00:00, 136.74it/s, loss=0.0123]


Loss: 0.9753038938108244
Accuracy: 0.7501372872048325
F1: 0.7836424155967665
Confusion Matrix: 
[[542  88]
 [367 824]]
Testing model
Loss: 1.0094645151070185
Accuracy: 0.7419724770642202
F1: 0.7743229689067201
Confusion Matrix: 
[[261  42]
 [183 386]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 137.24it/s, loss=0.711]


Loss: 0.6944123046439991
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 138.21it/s, loss=0.721]


Loss: 0.6315938893117403
Accuracy: 0.6501922020867655
F1: 0.7331378299120235
Confusion Matrix: 
[[309  37]
 [600 875]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 146.26it/s, loss=0.765]


Loss: 0.5727606698086387
Accuracy: 0.7682591982427238
F1: 0.7877263581488934
Confusion Matrix: 
[[616 129]
 [293 783]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 129.46it/s, loss=1.29]


Loss: 0.6087913426913714
Accuracy: 0.7808896210873146
F1: 0.7874267448055408
Confusion Matrix: 
[[683 173]
 [226 739]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:04<00:00, 147.84it/s, loss=0.403]


Loss: 0.7320123207673692
Accuracy: 0.7781438769906645
F1: 0.798
Confusion Matrix: 
[[619 114]
 [290 798]]
Testing model
Loss: 0.7394102332847459
Accuracy: 0.7786697247706422
F1: 0.7948990435706695
Confusion Matrix: 
[[305  54]
 [139 374]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 450,
    "num_layers": 3,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 0.25,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:09<00:00, 74.37it/s, loss=0.618]


Loss: 0.5058038663445857
Accuracy: 0.7457440966501923
F1: 0.7851508120649652
Confusion Matrix: 
[[512  66]
 [397 846]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:09<00:00, 72.06it/s, loss=0.334]


Loss: 0.48193223251585376
Accuracy: 0.8061504667764964
F1: 0.805937328202309
Confusion Matrix: 
[[735 179]
 [174 733]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:09<00:00, 72.91it/s, loss=0.761]


Loss: 0.678880532582601
Accuracy: 0.7589236683141132
F1: 0.7090788601722995
Confusion Matrix: 
[[847 377]
 [ 62 535]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:09<00:00, 72.85it/s, loss=0.66]


Loss: 0.732147525538478
Accuracy: 0.7309170785282811
F1: 0.66484268125855
Confusion Matrix: 
[[845 426]
 [ 64 486]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:09<00:00, 74.42it/s, loss=0.416]


Loss: 0.8475764540203831
Accuracy: 0.7462932454695222
F1: 0.7034659820282413
Confusion Matrix: 
[[811 364]
 [ 98 548]]
Testing model
Loss: 0.8825547777648483
Accuracy: 0.7396788990825688
F1: 0.6936572199730094
Confusion Matrix: 
[[388 171]
 [ 56 257]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 79.65it/s, loss=0.0593]


Loss: 0.8027330208242985
Accuracy: 0.742998352553542
F1: 0.6807639836289222
Confusion Matrix: 
[[854 413]
 [ 55 499]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 79.50it/s, loss=0.759]


Loss: 0.9920319394584287
Accuracy: 0.7303679297089511
F1: 0.6684672518568535
Confusion Matrix: 
[[835 417]
 [ 74 495]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 85.45it/s, loss=0.00206]


Loss: 1.1950848374450416
Accuracy: 0.7688083470620538
F1: 0.7446937537901759
Confusion Matrix: 
[[786 298]
 [123 614]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:08<00:00, 79.28it/s, loss=0.323]


Loss: 1.6553078169624011
Accuracy: 0.7073036792970895
F1: 0.623321554770318
Confusion Matrix: 
[[847 471]
 [ 62 441]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:08<00:00, 79.74it/s, loss=0.562]


Loss: 1.1777518179855848
Accuracy: 0.7034596375617792
F1: 0.6186440677966102
Confusion Matrix: 
[[843 474]
 [ 66 438]]
Testing model
Loss: 1.2300989792150046
Accuracy: 0.7006880733944955
F1: 0.6144756277695717
Confusion Matrix: 
[[403 220]
 [ 41 208]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 102.21it/s, loss=0.432]


Loss: 1.0403998149068732
Accuracy: 0.7671609006040637
F1: 0.735330836454432
Confusion Matrix: 
[[808 323]
 [101 589]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 91.97it/s, loss=0.437]


Loss: 1.3192993303140004
Accuracy: 0.7375068643602416
F1: 0.678763440860215
Confusion Matrix: 
[[838 407]
 [ 71 505]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 99.91it/s, loss=1.15]


Loss: 1.7497903098139846
Accuracy: 0.700164744645799
F1: 0.6002928257686676
Confusion Matrix: 
[[865 502]
 [ 44 410]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:07<00:00, 90.85it/s, loss=0.508] 


Loss: 1.7617985993100886
Accuracy: 0.7259747391543108
F1: 0.6815571155073389
Confusion Matrix: 
[[788 378]
 [121 534]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:06<00:00, 100.99it/s, loss=0.00924]


Loss: 1.26772285082884
Accuracy: 0.6968698517298187
F1: 0.6051502145922747
Confusion Matrix: 
[[846 489]
 [ 63 423]]
Testing model
Loss: 1.2821840510836668
Accuracy: 0.6972477064220184
F1: 0.6094674556213018
Confusion Matrix: 
[[402 222]
 [ 42 206]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 150,
    "num_layers": 2,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 0.25,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 109.93it/s, loss=0.897]


Loss: 0.5932461405009554
Accuracy: 0.71444261394838
F1: 0.7031963470319634
Confusion Matrix: 
[[685 296]
 [224 616]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 120.99it/s, loss=0.299]


Loss: 0.5164113251263636
Accuracy: 0.756727073036793
F1: 0.7316777710478498
Confusion Matrix: 
[[774 308]
 [135 604]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 101.61it/s, loss=0.183]


Loss: 0.5653880327417139
Accuracy: 0.7561779242174629
F1: 0.7168367346938775
Confusion Matrix: 
[[815 350]
 [ 94 562]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 116.83it/s, loss=0.0945]


Loss: 0.6820813427891648
Accuracy: 0.7545304777594728
F1: 0.71216999356085
Confusion Matrix: 
[[821 359]
 [ 88 553]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:06<00:00, 104.64it/s, loss=0.0335]


Loss: 1.1005798782172955
Accuracy: 0.7204832509610104
F1: 0.6372059871703493
Confusion Matrix: 
[[865 465]
 [ 44 447]]
Testing model
Loss: 1.0569241478307438
Accuracy: 0.7350917431192661
F1: 0.6627737226277373
Confusion Matrix: 
[[414 201]
 [ 30 227]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 122.85it/s, loss=1.25]


Loss: 0.6532153178725326
Accuracy: 0.71334431630972
F1: 0.66015625
Confusion Matrix: 
[[792 405]
 [117 507]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 108.39it/s, loss=0.429]


Loss: 1.2892547384427304
Accuracy: 0.6963207029104888
F1: 0.5942773294203962
Confusion Matrix: 
[[863 507]
 [ 46 405]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:05<00:00, 118.68it/s, loss=0.462]


Loss: 1.312909656710792
Accuracy: 0.71444261394838
F1: 0.6296296296296297
Confusion Matrix: 
[[859 470]
 [ 50 442]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:06<00:00, 104.70it/s, loss=0.506]


Loss: 1.3796321343173061
Accuracy: 0.729818780889621
F1: 0.6643929058663028
Confusion Matrix: 
[[842 425]
 [ 67 487]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:05<00:00, 117.28it/s, loss=0.34]


Loss: 1.1556024105663885
Accuracy: 0.7468423942888522
F1: 0.7061822817080943
Confusion Matrix: 
[[806 358]
 [103 554]]
Testing model
Loss: 1.1784126402011939
Accuracy: 0.7522935779816514
F1: 0.7112299465240641
Confusion Matrix: 
[[390 162]
 [ 54 266]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 136.97it/s, loss=0.592]


Loss: 0.5578176894208842
Accuracy: 0.7594728171334432
F1: 0.7792338709677419
Confusion Matrix: 
[[610 139]
 [299 773]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 132.92it/s, loss=0.0097]


Loss: 1.0226689409791379
Accuracy: 0.7627677100494233
F1: 0.722007722007722
Confusion Matrix: 
[[828 351]
 [ 81 561]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 143.79it/s, loss=0.00661]


Loss: 0.9667350030259082
Accuracy: 0.7918725974739155
F1: 0.7807981492192019
Confusion Matrix: 
[[767 237]
 [142 675]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 135.76it/s, loss=0.465]


Loss: 0.9799162538950903
Accuracy: 0.7902251510159253
F1: 0.7771295215869312
Confusion Matrix: 
[[773 246]
 [136 666]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:04<00:00, 145.45it/s, loss=0.0045]


Loss: 1.100050958886481
Accuracy: 0.7913234486545854
F1: 0.7775175644028103
Confusion Matrix: 
[[777 248]
 [132 664]]
Testing model
Loss: 1.1836470542475581
Accuracy: 0.7763761467889908
F1: 0.7619047619047619
Confusion Matrix: 
[[365 116]
 [ 79 312]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 150,
    "num_layers": 15,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 0.25,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:15<00:00, 43.31it/s, loss=0.701]


Loss: 0.6939392037558973
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:16<00:00, 42.78it/s, loss=0.687]


Loss: 0.6937772328393501
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:16<00:00, 41.68it/s, loss=0.678]


Loss: 0.6940183440844218
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:16<00:00, 42.83it/s, loss=0.694]


Loss: 0.694241019717434
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:15<00:00, 43.27it/s, loss=0.685]


Loss: 0.694223894361864
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Testing model
Loss: 0.6944899239710399
Accuracy: 0.5091743119266054
F1: 0.0
Confusion Matrix: 
[[444 428]
 [  0   0]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:15<00:00, 43.73it/s, loss=0.742]


Loss: 0.5400631767615938
Accuracy: 0.7380560131795717
F1: 0.716913946587537
Confusion Matrix: 
[[740 308]
 [169 604]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:15<00:00, 45.83it/s, loss=0.155]


Loss: 0.4968094663661823
Accuracy: 0.7913234486545854
F1: 0.786036036036036
Confusion Matrix: 
[[743 214]
 [166 698]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:15<00:00, 45.81it/s, loss=0.714]


Loss: 0.6443724323783004
Accuracy: 0.7627677100494233
F1: 0.7902912621359224
Confusion Matrix: 
[[575  98]
 [334 814]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:14<00:00, 46.16it/s, loss=0.69]


Loss: 0.7567807062153231
Accuracy: 0.7556287753981329
F1: 0.7907851433944523
Confusion Matrix: 
[[535  71]
 [374 841]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:15<00:00, 46.11it/s, loss=0.297]


Loss: 0.528402201439205
Accuracy: 0.7775947281713345
F1: 0.8048192771084337
Confusion Matrix: 
[[581  77]
 [328 835]]
Testing model
Loss: 0.5624825246632099
Accuracy: 0.7568807339449541
F1: 0.7832310838445807
Confusion Matrix: 
[[277  45]
 [167 383]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 89.17it/s, loss=0.711] 


Loss: 0.6943091739688003
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 98.85it/s, loss=0.723]


Loss: 0.700554234939709
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:07<00:00, 89.82it/s, loss=0.694]


Loss: 0.6941579015631425
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:07<00:00, 93.48it/s, loss=0.734]


Loss: 0.6959369956401357
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:07<00:00, 96.09it/s, loss=0.689] 


Loss: 0.694385760708859
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Testing model
Loss: 0.6946718373468944
Accuracy: 0.5091743119266054
F1: 0.0
Confusion Matrix: 
[[444 428]
 [  0   0]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 150,
    "num_layers": 3,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": True,
    "dropout": 0.25,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:09<00:00, 73.35it/s, loss=0.358]


Loss: 0.5048997057111639
Accuracy: 0.7616694124107634
F1: 0.7887049659201558
Confusion Matrix: 
[[577 102]
 [332 810]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:09<00:00, 72.48it/s, loss=0.387]


Loss: 0.44165911250992823
Accuracy: 0.7968149368478857
F1: 0.7800237812128419
Confusion Matrix: 
[[795 256]
 [114 656]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:09<00:00, 74.05it/s, loss=0.599]


Loss: 0.47160333656428155
Accuracy: 0.7990115321252059
F1: 0.8157099697885196
Confusion Matrix: 
[[645 102]
 [264 810]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:08<00:00, 80.08it/s, loss=0.0369]


Loss: 0.63991843895954
Accuracy: 0.8012081274025261
F1: 0.7800729040097205
Confusion Matrix: 
[[817 270]
 [ 92 642]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:09<00:00, 72.87it/s, loss=0.00563]


Loss: 0.6691366854989738
Accuracy: 0.8138385502471169
F1: 0.8287013643254169
Confusion Matrix: 
[[662  92]
 [247 820]]
Testing model
Loss: 0.7545429973730019
Accuracy: 0.7924311926605505
F1: 0.8076514346439958
Confusion Matrix: 
[[311  48]
 [133 380]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:09<00:00, 75.13it/s, loss=0.619]


Loss: 0.5554659609731875
Accuracy: 0.8039538714991763
F1: 0.8096
Confusion Matrix: 
[[705 153]
 [204 759]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 82.05it/s, loss=0.379]


Loss: 0.5418828197738581
Accuracy: 0.8138385502471169
F1: 0.8079320113314448
Confusion Matrix: 
[[769 199]
 [140 713]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 77.44it/s, loss=0.0214]


Loss: 0.5219483203009555
Accuracy: 0.8176825919824272
F1: 0.8224598930481284
Confusion Matrix: 
[[720 143]
 [189 769]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:09<00:00, 75.76it/s, loss=0.735]


Loss: 0.8576523504759136
Accuracy: 0.8204283360790774
F1: 0.829064296915839
Confusion Matrix: 
[[701 119]
 [208 793]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:08<00:00, 81.05it/s, loss=0.00266]


Loss: 0.9650154516362307
Accuracy: 0.800658978583196
F1: 0.7843137254901961
Confusion Matrix: 
[[798 252]
 [111 660]]
Testing model
Loss: 1.0255506451940164
Accuracy: 0.7970183486238532
F1: 0.7773584905660378
Confusion Matrix: 
[[386 119]
 [ 58 309]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 116.98it/s, loss=0.508]


Loss: 0.6443057055013222
Accuracy: 0.7029104887424492
F1: 0.7632385120350109
Confusion Matrix: 
[[408  40]
 [501 872]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 128.15it/s, loss=0.619]


Loss: 0.7861645002114145
Accuracy: 0.785831960461285
F1: 0.8090107737512243
Confusion Matrix: 
[[605  86]
 [304 826]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 113.58it/s, loss=0.00672]


Loss: 0.8449916983382744
Accuracy: 0.8116419549697969
F1: 0.8210745957224831
Confusion Matrix: 
[[691 125]
 [218 787]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 128.19it/s, loss=0.00268]


Loss: 1.0964904417071426
Accuracy: 0.7984623833058759
F1: 0.7943977591036414
Confusion Matrix: 
[[745 203]
 [164 709]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:05<00:00, 115.54it/s, loss=0.00481]


Loss: 0.9992258187971617
Accuracy: 0.8012081274025261
F1: 0.8139773895169579
Confusion Matrix: 
[[667 120]
 [242 792]]
Testing model
Loss: 1.0685373087014471
Accuracy: 0.7889908256880734
F1: 0.7973568281938326
Confusion Matrix: 
[[326  66]
 [118 362]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 150,
    "num_layers": 3,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 0,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 94.97it/s, loss=0.5] 


Loss: 0.6493921005412152
Accuracy: 0.7473915431081823
F1: 0.7181372549019608
Confusion Matrix: 
[[775 326]
 [134 586]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 106.83it/s, loss=0.406]


Loss: 0.45041725091766893
Accuracy: 0.7891268533772653
F1: 0.807035175879397
Confusion Matrix: 
[[634 109]
 [275 803]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:07<00:00, 94.84it/s, loss=0.7] 


Loss: 0.6863148034664622
Accuracy: 0.7808896210873146
F1: 0.7550644567219152
Confusion Matrix: 
[[807 297]
 [102 615]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:06<00:00, 105.90it/s, loss=0.233]


Loss: 0.4528362552324931
Accuracy: 0.8088962108731467
F1: 0.8110749185667753
Confusion Matrix: 
[[726 165]
 [183 747]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:07<00:00, 96.02it/s, loss=0.3] 


Loss: 0.5889754977665449
Accuracy: 0.8182317408017573
F1: 0.818431157432803
Confusion Matrix: 
[[744 166]
 [165 746]]
Testing model
Loss: 0.6290872836751598
Accuracy: 0.8142201834862385
F1: 0.8146453089244852
Confusion Matrix: 
[[354  72]
 [ 90 356]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 108.23it/s, loss=0.804]


Loss: 0.5164895355701447
Accuracy: 0.7803404722679846
F1: 0.7674418604651163
Confusion Matrix: 
[[761 252]
 [148 660]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 101.47it/s, loss=0.684]


Loss: 0.8570066332294229
Accuracy: 0.7523338824821527
F1: 0.7023102310231023
Confusion Matrix: 
[[838 380]
 [ 71 532]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 107.62it/s, loss=0.14]


Loss: 1.1962113669305516
Accuracy: 0.7232289950576606
F1: 0.6420454545454546
Confusion Matrix: 
[[865 460]
 [ 44 452]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:06<00:00, 100.87it/s, loss=0.00593]


Loss: 1.3492061359840526
Accuracy: 0.7408017572762219
F1: 0.6853333333333333
Confusion Matrix: 
[[835 398]
 [ 74 514]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:06<00:00, 105.55it/s, loss=0.00184]


Loss: 1.5639494299365764
Accuracy: 0.7320153761669412
F1: 0.6702702702702703
Confusion Matrix: 
[[837 416]
 [ 72 496]]
Testing model
Loss: 1.637335510126182
Accuracy: 0.7213302752293578
F1: 0.6503597122302158
Confusion Matrix: 
[[403 202]
 [ 41 226]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 130.25it/s, loss=0.339]


Loss: 0.5745017131169637
Accuracy: 0.7984623833058759
F1: 0.8046833422032996
Confusion Matrix: 
[[698 156]
 [211 756]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:04<00:00, 144.52it/s, loss=0.0322]


Loss: 0.6674746421345493
Accuracy: 0.8012081274025261
F1: 0.7938496583143508
Confusion Matrix: 
[[762 215]
 [147 697]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:05<00:00, 133.44it/s, loss=0.00955]


Loss: 1.0563116078836876
Accuracy: 0.7737506864360242
F1: 0.7541766109785203
Confusion Matrix: 
[[777 280]
 [132 632]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:04<00:00, 141.56it/s, loss=0.00893]


Loss: 1.2407987297496252
Accuracy: 0.7391543108182317
F1: 0.6744345442083619
Confusion Matrix: 
[[854 420]
 [ 55 492]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:04<00:00, 144.78it/s, loss=0.533]


Loss: 1.0479688171231956
Accuracy: 0.7979132344865458
F1: 0.805702217529039
Confusion Matrix: 
[[690 149]
 [219 763]]
Testing model
Loss: 1.127778603479133
Accuracy: 0.7775229357798165
F1: 0.780045351473923
Confusion Matrix: 
[[334  84]
 [110 344]]


In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "hidden_size": 150,
    "num_layers": 3,
    "embedding_dim": 300,
    "epochs": 5,
    "bidirectional": False,
    "dropout": 1,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

main(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 93.91it/s, loss=0.685]


Loss: 0.6943989301982679
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 106.86it/s, loss=0.68]


Loss: 0.693885606631898
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:07<00:00, 95.90it/s, loss=0.687] 


Loss: 0.6939119267881962
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:06<00:00, 105.78it/s, loss=0.694]


Loss: 0.6940851389316091
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:07<00:00, 93.33it/s, loss=0.698] 


Loss: 0.6935446617896097
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Testing model
Loss: 0.6936905660799572
Accuracy: 0.5091743119266054
F1: 0.0
Confusion Matrix: 
[[444 428]
 [  0   0]]
Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 109.61it/s, loss=0.721]


Loss: 0.6947828625377855
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 97.07it/s, loss=0.717] 


Loss: 0.6943677161869249
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 108.87it/s, loss=0.695]


Loss: 0.6947728468660723
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:07<00:00, 97.58it/s, loss=0.72] 


Loss: 0.6947941821918153
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:06<00:00, 110.34it/s, loss=0.673]


Loss: 0.6943507016750804
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Testing model
Loss: 0.6945764060531344
Accuracy: 0.5091743119266054
F1: 0.0
Confusion Matrix: 
[[444 428]
 [  0   0]]
Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 128.66it/s, loss=0.695]


Loss: 0.6957863067325792
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:04<00:00, 144.28it/s, loss=0.694]


Loss: 0.6938319802284241
Accuracy: 0.5019220208676551
F1: 0.010905125408942203
Confusion Matrix: 
[[909 907]
 [  0   5]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 139.04it/s, loss=0.706]


Loss: 0.6951330513284918
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 4


Training: 100%|██████████| 692/692 [00:05<00:00, 130.87it/s, loss=0.685]


Loss: 0.6945508519808451
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 5


Training: 100%|██████████| 692/692 [00:04<00:00, 144.12it/s, loss=0.704]


Loss: 0.6946886370056554
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Testing model
Loss: 0.6948226903166089
Accuracy: 0.5091743119266054
F1: 0.0
Confusion Matrix: 
[[444 428]
 [  0   0]]


In [ ]:
def grid_search(args):
  seed = args.seed

  model_type = ['LSTM']
  hidden_size = [150, 300]
  num_layers = [3, 10]
  bidirectional = [True, False]
  dropout = [0.05, 0.25]
  best_f1 = 0
  best_model_state = None
  best_params = None

  train_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_train_raw.csv')
  valid_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_valid_raw.csv')
  test_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_test_raw.csv')
  vocab = train_dataset.text_vocab
  valid_dataset.text_vocab = vocab
  test_dataset.text_vocab = vocab
  valid_dataset.label_vocab = train_dataset.label_vocab
  test_dataset.label_vocab = train_dataset.label_vocab

  train_dataloader = DataLoader(dataset=train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=pad_collate_fn)
  valid_dataloader = DataLoader(dataset=valid_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)
  test_dataloader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

  embedding = Embedding(vocab, '/content/drive/MyDrive/Colab Notebooks/sst_glove_6b_300d.txt', args.embedding_dim)
  np.random.seed(seed)
  torch.manual_seed(seed)

  for type_ in model_type:
    print(f"Model type: {type_}")
    for hs, nl, bi, dp in itertools.product(hidden_size, num_layers, bidirectional, dropout):
      model = RNN(type_, embedding=embedding, input_size=args.embedding_dim, hidden_size=hs, num_layers=nl, bidirectional=bi, dropout=dp)
      model.to(args.device)

      criterion = nn.BCEWithLogitsLoss()
      optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

      for epoch in range(args.epochs):
        print(f"Epoch: {epoch+1}")
        train(model, train_dataloader, optimizer, criterion, args)
        evaluate(model, valid_dataloader, criterion, args)

      val_loss, val_acc, val_f1, val_cm = evaluate(model, valid_dataloader, criterion, args)

      if val_f1 > best_f1:
            best_f1 = val_f1
            best_model_state = model.state_dict()
            best_params = {
                'model_type': type_,
                'hidden_size': hs,
                'num_layers': nl,
                'dropout': dp,
                'bidirectional': bi
            }
            torch.save({'model_state_dict': best_model_state, 'params': best_params}, 'best_params_LSTM.pt')

    print("Testing model")
    evaluate(model, test_dataloader, criterion, args)

  print("\n Grid search finished.")
  print(f"Best F1-score: {best_f1:.4f}")
  print(f"Best hyperparameters: {best_params}")

In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "embedding_dim": 300,
    "epochs": 3,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

grid_search(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: LSTM
Epoch: 1


Training: 100%|██████████| 692/692 [00:09<00:00, 71.93it/s, loss=0.391]


Loss: 0.5515666734753993
Accuracy: 0.7462932454695222
F1: 0.7820754716981132
Confusion Matrix: 
[[530  83]
 [379 829]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:09<00:00, 73.15it/s, loss=0.318]


Loss: 0.5401753720484281
Accuracy: 0.7699066447007139
F1: 0.7891293407146452
Confusion Matrix: 
[[618 128]
 [291 784]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 80.26it/s, loss=0.654]


Loss: 0.6310955445494568
Accuracy: 0.7265238879736409
F1: 0.7740471869328494
Confusion Matrix: 
[[470  59]
 [439 853]]
Loss: 0.6310955445494568
Accuracy: 0.7265238879736409
F1: 0.7740471869328494
Confusion Matrix: 
[[470  59]
 [439 853]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:09<00:00, 74.34it/s, loss=0.275]


Loss: 0.49469659124550064
Accuracy: 0.7753981328940143
F1: 0.8013598834385625
Confusion Matrix: 
[[587  87]
 [322 825]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:09<00:00, 73.40it/s, loss=0.428]


Loss: 0.5038208964101055
Accuracy: 0.7825370675453048
F1: 0.8055009823182712
Confusion Matrix: 
[[605  92]
 [304 820]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:09<00:00, 73.73it/s, loss=0.248]


Loss: 0.5308577352971361
Accuracy: 0.7891268533772653
F1: 0.8113948919449901
Confusion Matrix: 
[[611  86]
 [298 826]]
Loss: 0.5308577352971361
Accuracy: 0.7891268533772653
F1: 0.8113948919449901
Confusion Matrix: 
[[611  86]
 [298 826]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 104.94it/s, loss=0.202]


Loss: 0.586564112127873
Accuracy: 0.7682591982427238
F1: 0.7860040567951319
Confusion Matrix: 
[[624 137]
 [285 775]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 95.88it/s, loss=0.134] 


Loss: 0.6432817089453078
Accuracy: 0.7847336628226249
F1: 0.8047808764940239
Confusion Matrix: 
[[621 104]
 [288 808]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 107.95it/s, loss=0.787]


Loss: 0.8236486859488905
Accuracy: 0.7742998352553542
F1: 0.7958271236959762
Confusion Matrix: 
[[609 111]
 [300 801]]
Loss: 0.8236486859488905
Accuracy: 0.7742998352553542
F1: 0.7958271236959762
Confusion Matrix: 
[[609 111]
 [300 801]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 94.48it/s, loss=0.0292] 


Loss: 0.7608954503870847
Accuracy: 0.7677100494233937
F1: 0.7957508450024143
Confusion Matrix: 
[[574  88]
 [335 824]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 106.34it/s, loss=0.00938]


Loss: 0.9772308583845172
Accuracy: 0.7764964305326744
F1: 0.7822364901016586
Confusion Matrix: 
[[683 181]
 [226 731]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:07<00:00, 93.27it/s, loss=0.278] 


Loss: 0.9452804719146929
Accuracy: 0.771554091158704
F1: 0.7974683544303798
Confusion Matrix: 
[[586  93]
 [323 819]]
Loss: 0.9452804719146929
Accuracy: 0.771554091158704
F1: 0.7974683544303798
Confusion Matrix: 
[[586  93]
 [323 819]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:19<00:00, 35.37it/s, loss=0.671]


Loss: 0.6445547486083549
Accuracy: 0.7336628226249313
F1: 0.7796456156292594
Confusion Matrix: 
[[478  54]
 [431 858]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:19<00:00, 35.35it/s, loss=0.362]


Loss: 0.9415559558230534
Accuracy: 0.742449203734212
F1: 0.7849610270518111
Confusion Matrix: 
[[496  56]
 [413 856]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:20<00:00, 34.13it/s, loss=0.00339]


Loss: 1.210161080812676
Accuracy: 0.7600219659527732
F1: 0.792003807710614
Confusion Matrix: 
[[552  80]
 [357 832]]
Loss: 1.210161080812676
Accuracy: 0.7600219659527732
F1: 0.792003807710614
Confusion Matrix: 
[[552  80]
 [357 832]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:19<00:00, 35.69it/s, loss=0.348]


Loss: 0.6135066109791136
Accuracy: 0.7836353651839648
F1: 0.8012108980827447
Confusion Matrix: 
[[633 118]
 [276 794]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:19<00:00, 35.23it/s, loss=0.00566]


Loss: 0.994860622182227
Accuracy: 0.7808896210873146
F1: 0.8052708638360175
Confusion Matrix: 
[[597  87]
 [312 825]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:20<00:00, 33.77it/s, loss=0.00291]


Loss: 0.9963427085527464
Accuracy: 0.8072487644151565
F1: 0.8202764976958525
Confusion Matrix: 
[[669 111]
 [240 801]]
Loss: 0.9963427085527464
Accuracy: 0.8072487644151565
F1: 0.8202764976958525
Confusion Matrix: 
[[669 111]
 [240 801]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:12<00:00, 54.67it/s, loss=0.372]


Loss: 0.6818645235739256
Accuracy: 0.7869302580999451
F1: 0.776239907727797
Confusion Matrix: 
[[760 239]
 [149 673]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:12<00:00, 54.66it/s, loss=0.0389]


Loss: 1.0403993443438881
Accuracy: 0.7935200439319056
F1: 0.8055842812823164
Confusion Matrix: 
[[666 133]
 [243 779]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:12<00:00, 55.32it/s, loss=0.00224]


Loss: 1.1004794122357118
Accuracy: 0.7907742998352554
F1: 0.7987321711568938
Confusion Matrix: 
[[684 156]
 [225 756]]
Loss: 1.1004794122357118
Accuracy: 0.7907742998352554
F1: 0.7987321711568938
Confusion Matrix: 
[[684 156]
 [225 756]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:12<00:00, 55.04it/s, loss=0.0653]


Loss: 0.7670471015990826
Accuracy: 0.7303679297089511
F1: 0.7801164352888491
Confusion Matrix: 
[[459  41]
 [450 871]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:12<00:00, 54.90it/s, loss=1.24]


Loss: 1.219712646906836
Accuracy: 0.7671609006040637
F1: 0.793974732750243
Confusion Matrix: 
[[580  95]
 [329 817]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:12<00:00, 54.94it/s, loss=0.595]


Loss: 1.308693547782145
Accuracy: 0.7699066447007139
F1: 0.7965031568722681
Confusion Matrix: 
[[582  92]
 [327 820]]
Loss: 1.308693547782145
Accuracy: 0.7699066447007139
F1: 0.7965031568722681
Confusion Matrix: 
[[582  92]
 [327 820]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:11<00:00, 58.06it/s, loss=0.00123]


Loss: 1.3884282987891583
Accuracy: 0.757276221856123
F1: 0.7919020715630886
Confusion Matrix: 
[[538  71]
 [371 841]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:11<00:00, 58.30it/s, loss=0.468]


Loss: 1.4343280661524387
Accuracy: 0.7611202635914333
F1: 0.7927584564078133
Confusion Matrix: 
[[554  80]
 [355 832]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:11<00:00, 58.33it/s, loss=0.000813]


Loss: 1.4617917725914402
Accuracy: 0.7792421746293245
F1: 0.7912772585669782
Confusion Matrix: 
[[657 150]
 [252 762]]
Loss: 1.4617917725914402
Accuracy: 0.7792421746293245
F1: 0.7912772585669782
Confusion Matrix: 
[[657 150]
 [252 762]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:11<00:00, 58.31it/s, loss=0.425]


Loss: 1.4833481395453738
Accuracy: 0.7693574958813838
F1: 0.7974927675988428
Confusion Matrix: 
[[574  85]
 [335 827]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:11<00:00, 58.21it/s, loss=0.000569]


Loss: 1.7784019278182663
Accuracy: 0.742449203734212
F1: 0.7847636530518587
Confusion Matrix: 
[[497  57]
 [412 855]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:11<00:00, 57.82it/s, loss=0.000991]


Loss: 1.5122442148756563
Accuracy: 0.7622185612300933
F1: 0.7948839412600663
Confusion Matrix: 
[[549  73]
 [360 839]]
Loss: 1.5122442148756563
Accuracy: 0.7622185612300933
F1: 0.7948839412600663
Confusion Matrix: 
[[549  73]
 [360 839]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 89.02it/s, loss=0.000954]


Loss: 1.389382065911042
Accuracy: 0.7523338824821527
F1: 0.7822308063737325
Confusion Matrix: 
[[560 102]
 [349 810]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 80.62it/s, loss=0.000846]


Loss: 1.5424772537591165
Accuracy: 0.7605711147721033
F1: 0.7811244979919679
Confusion Matrix: 
[[607 134]
 [302 778]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 84.52it/s, loss=0.000488]


Loss: 1.7285704076812978
Accuracy: 0.7583745194947831
F1: 0.7910731244064577
Confusion Matrix: 
[[548  79]
 [361 833]]
Loss: 1.7285704076812978
Accuracy: 0.7583745194947831
F1: 0.7910731244064577
Confusion Matrix: 
[[548  79]
 [361 833]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 85.67it/s, loss=0.00274]


Loss: 1.35067525061599
Accuracy: 0.7583745194947831
F1: 0.7857838364167478
Confusion Matrix: 
[[574 105]
 [335 807]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 80.01it/s, loss=0.00037]


Loss: 1.6471242279860012
Accuracy: 0.7578253706754531
F1: 0.7860262008733624
Confusion Matrix: 
[[570 102]
 [339 810]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:07<00:00, 87.06it/s, loss=0.00112]


Loss: 1.675930441332687
Accuracy: 0.7512355848434926
F1: 0.7854097584083373
Confusion Matrix: 
[[539  83]
 [370 829]]
Loss: 1.675930441332687
Accuracy: 0.7512355848434926
F1: 0.7854097584083373
Confusion Matrix: 
[[539  83]
 [370 829]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:30<00:00, 23.03it/s, loss=0.442]


Loss: 0.6123738466647634
Accuracy: 0.7408017572762219
F1: 0.7623363544813696
Confusion Matrix: 
[[592 155]
 [317 757]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:29<00:00, 23.44it/s, loss=0.00745]


Loss: 1.1764488071203232
Accuracy: 0.7539813289401428
F1: 0.7850287907869482
Confusion Matrix: 
[[555  94]
 [354 818]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:29<00:00, 23.53it/s, loss=0.000718]


Loss: 1.359362023441415
Accuracy: 0.7847336628226249
F1: 0.7997957099080695
Confusion Matrix: 
[[646 129]
 [263 783]]
Loss: 1.359362023441415
Accuracy: 0.7847336628226249
F1: 0.7997957099080695
Confusion Matrix: 
[[646 129]
 [263 783]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:29<00:00, 23.27it/s, loss=0.00449]


Loss: 1.195119767923627
Accuracy: 0.7737506864360242
F1: 0.8028708133971292
Confusion Matrix: 
[[570  73]
 [339 839]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:29<00:00, 23.41it/s, loss=0.00176]


Loss: 1.3588762223197703
Accuracy: 0.7869302580999451
F1: 0.8034447821681864
Confusion Matrix: 
[[640 119]
 [269 793]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:30<00:00, 22.99it/s, loss=0.000539]


Loss: 1.753361067828608
Accuracy: 0.7545304777594728
F1: 0.790632318501171
Confusion Matrix: 
[[530  68]
 [379 844]]
Loss: 1.753361067828608
Accuracy: 0.7545304777594728
F1: 0.790632318501171
Confusion Matrix: 
[[530  68]
 [379 844]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:16<00:00, 42.60it/s, loss=0.571]


Loss: 1.231155081799156
Accuracy: 0.7682591982427238
F1: 0.7566320645905421
Confusion Matrix: 
[[743 256]
 [166 656]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:16<00:00, 42.58it/s, loss=0.000685]


Loss: 1.6655959335621446
Accuracy: 0.7314662273476112
F1: 0.7766103243490178
Confusion Matrix: 
[[482  62]
 [427 850]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:16<00:00, 41.69it/s, loss=0.484]


Loss: 1.7111790394308373
Accuracy: 0.7539813289401428
F1: 0.7902621722846442
Confusion Matrix: 
[[529  68]
 [380 844]]
Loss: 1.7111790394308373
Accuracy: 0.7539813289401428
F1: 0.7902621722846442
Confusion Matrix: 
[[529  68]
 [380 844]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:16<00:00, 41.86it/s, loss=0.000752]


Loss: 1.5375832290503018
Accuracy: 0.7726523887973641
F1: 0.7960591133004926
Confusion Matrix: 
[[599 104]
 [310 808]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:16<00:00, 42.13it/s, loss=0.00125]


Loss: 1.7286892402590366
Accuracy: 0.7616694124107634
F1: 0.7872549019607843
Confusion Matrix: 
[[584 109]
 [325 803]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:16<00:00, 42.34it/s, loss=0.000646]


Loss: 1.8895217807669389
Accuracy: 0.7545304777594728
F1: 0.7874465049928673
Confusion Matrix: 
[[546  84]
 [363 828]]
Loss: 1.8895217807669389
Accuracy: 0.7545304777594728
F1: 0.7874465049928673
Confusion Matrix: 
[[546  84]
 [363 828]]
Testing model
Loss: 1.9319967227477588
Accuracy: 0.7477064220183486
F1: 0.779559118236473
Confusion Matrix: 
[[263  39]
 [181 389]]

 Grid search finished.
Best F1-score: 0.8203
Best hyperparameters: {'model_type': 'LSTM', 'hidden_size': 150, 'num_layers': 10, 'dropout': 0.25, 'bidirectional': True}


In [ ]:
def grid_search(args):
  seed = args.seed

  model_type = ['GRU']
  hidden_size = [150, 300]
  num_layers = [3, 10]
  bidirectional = [True, False]
  dropout = [0.05, 0.25]
  best_f1 = 0
  best_model_state = None
  best_params = None

  train_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_train_raw.csv')
  valid_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_valid_raw.csv')
  test_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_test_raw.csv')
  vocab = train_dataset.text_vocab
  valid_dataset.text_vocab = vocab
  test_dataset.text_vocab = vocab
  valid_dataset.label_vocab = train_dataset.label_vocab
  test_dataset.label_vocab = train_dataset.label_vocab

  train_dataloader = DataLoader(dataset=train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=pad_collate_fn)
  valid_dataloader = DataLoader(dataset=valid_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)
  test_dataloader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

  embedding = Embedding(vocab, '/content/drive/MyDrive/Colab Notebooks/sst_glove_6b_300d.txt', args.embedding_dim)
  np.random.seed(seed)
  torch.manual_seed(seed)

  for type_ in model_type:
    print(f"Model type: {type_}")
    for hs, nl, bi, dp in itertools.product(hidden_size, num_layers, bidirectional, dropout):
      model = RNN(type_, embedding=embedding, input_size=args.embedding_dim, hidden_size=hs, num_layers=nl, bidirectional=bi, dropout=dp)
      model.to(args.device)

      criterion = nn.BCEWithLogitsLoss()
      optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

      for epoch in range(args.epochs):
        print(f"Epoch: {epoch+1}")
        train(model, train_dataloader, optimizer, criterion, args)
        evaluate(model, valid_dataloader, criterion, args)

      val_loss, val_acc, val_f1, val_cm = evaluate(model, valid_dataloader, criterion, args)

      if val_f1 > best_f1:
            best_f1 = val_f1
            best_model_state = model.state_dict()
            best_params = {
                'model_type': type_,
                'hidden_size': hs,
                'num_layers': nl,
                'dropout': dp,
                'bidirectional': bi
            }
            torch.save({'model_state_dict': best_model_state, 'params': best_params}, 'best_params_GRU.pt')

    print("Testing model")
    evaluate(model, test_dataloader, criterion, args)

  print("\n Grid search finished.")
  print(f"Best F1-score: {best_f1:.4f}")
  print(f"Best hyperparameters: {best_params}")

In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "embedding_dim": 300,
    "epochs": 3,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

grid_search(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: GRU
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 78.20it/s, loss=0.285]


Loss: 0.49866078401866715
Accuracy: 0.7836353651839648
F1: 0.7888531618435155
Confusion Matrix: 
[[691 176]
 [218 736]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:09<00:00, 75.73it/s, loss=0.437]


Loss: 0.4685969674273541
Accuracy: 0.7808896210873146
F1: 0.8031573754316724
Confusion Matrix: 
[[608  98]
 [301 814]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 81.81it/s, loss=0.185]


Loss: 0.4579519571965201
Accuracy: 0.7957166392092258
F1: 0.8158415841584158
Confusion Matrix: 
[[625  88]
 [284 824]]
Loss: 0.4579519571965201
Accuracy: 0.7957166392092258
F1: 0.8158415841584158
Confusion Matrix: 
[[625  88]
 [284 824]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 78.64it/s, loss=0.595]


Loss: 0.48213388470181245
Accuracy: 0.8121911037891268
F1: 0.8067796610169492
Confusion Matrix: 
[[765 198]
 [144 714]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:09<00:00, 75.40it/s, loss=0.241]


Loss: 0.45318433720814555
Accuracy: 0.8193300384404174
F1: 0.8169170840289371
Confusion Matrix: 
[[758 178]
 [151 734]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 80.06it/s, loss=0.483]


Loss: 0.4882684595752181
Accuracy: 0.8066996155958265
F1: 0.7990867579908676
Confusion Matrix: 
[[769 212]
 [140 700]]
Loss: 0.4882684595752181
Accuracy: 0.8066996155958265
F1: 0.7990867579908676
Confusion Matrix: 
[[769 212]
 [140 700]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 104.88it/s, loss=0.43]


Loss: 0.5514139070322639
Accuracy: 0.7885777045579352
F1: 0.8064353946706888
Confusion Matrix: 
[[634 110]
 [275 802]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 104.06it/s, loss=0.749]


Loss: 0.7017921015881655
Accuracy: 0.7951674903898956
F1: 0.7751657625075347
Confusion Matrix: 
[[805 269]
 [104 643]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 103.90it/s, loss=0.183]


Loss: 0.6681440012496814
Accuracy: 0.8050521691378364
F1: 0.794679005205321
Confusion Matrix: 
[[779 225]
 [130 687]]
Loss: 0.6681440012496814
Accuracy: 0.8050521691378364
F1: 0.794679005205321
Confusion Matrix: 
[[779 225]
 [130 687]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 101.39it/s, loss=0.296]


Loss: 0.46914823928423094
Accuracy: 0.8165842943437671
F1: 0.822529224229543
Confusion Matrix: 
[[713 138]
 [196 774]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 105.89it/s, loss=0.867]


Loss: 0.8642413495925435
Accuracy: 0.8034047226798462
F1: 0.7869047619047619
Confusion Matrix: 
[[802 251]
 [107 661]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 99.77it/s, loss=0.569]


Loss: 0.8790287482633925
Accuracy: 0.8187808896210873
F1: 0.8170731707317073
Confusion Matrix: 
[[754 175]
 [155 737]]
Loss: 0.8790287482633925
Accuracy: 0.8187808896210873
F1: 0.8170731707317073
Confusion Matrix: 
[[754 175]
 [155 737]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:18<00:00, 37.55it/s, loss=0.0108]


Loss: 0.8173872248122567
Accuracy: 0.8061504667764964
F1: 0.8139167105956774
Confusion Matrix: 
[[696 140]
 [213 772]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:18<00:00, 38.22it/s, loss=0.458]


Loss: 1.03044353843781
Accuracy: 0.785282811641955
F1: 0.7545511613308223
Confusion Matrix: 
[[829 311]
 [ 80 601]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:18<00:00, 36.69it/s, loss=0.0169]


Loss: 0.939607902315625
Accuracy: 0.8127402526084568
F1: 0.806798866855524
Confusion Matrix: 
[[768 200]
 [141 712]]
Loss: 0.939607902315625
Accuracy: 0.8127402526084568
F1: 0.806798866855524
Confusion Matrix: 
[[768 200]
 [141 712]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:18<00:00, 38.18it/s, loss=0.388]


Loss: 0.9192300904215428
Accuracy: 0.8127402526084568
F1: 0.80831928049466
Confusion Matrix: 
[[761 193]
 [148 719]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:19<00:00, 36.09it/s, loss=1.06]


Loss: 1.0575597288838603
Accuracy: 0.8012081274025261
F1: 0.8197211155378487
Confusion Matrix: 
[[636  89]
 [273 823]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:18<00:00, 37.51it/s, loss=0.00156]


Loss: 1.189335596559798
Accuracy: 0.800109829763866
F1: 0.8192651439920556
Confusion Matrix: 
[[632  87]
 [277 825]]
Loss: 1.189335596559798
Accuracy: 0.800109829763866
F1: 0.8192651439920556
Confusion Matrix: 
[[632  87]
 [277 825]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:12<00:00, 57.54it/s, loss=0.53]


Loss: 0.9074551044848927
Accuracy: 0.7957166392092258
F1: 0.7847222222222222
Confusion Matrix: 
[[771 234]
 [138 678]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:12<00:00, 57.36it/s, loss=1.08]


Loss: 1.2308865393462933
Accuracy: 0.7578253706754531
F1: 0.7054108216432866
Confusion Matrix: 
[[852 384]
 [ 57 528]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:12<00:00, 57.36it/s, loss=0.614]


Loss: 1.2789499615890938
Accuracy: 0.7627677100494233
F1: 0.7194805194805195
Confusion Matrix: 
[[835 358]
 [ 74 554]]
Loss: 1.2789499615890938
Accuracy: 0.7627677100494233
F1: 0.7194805194805195
Confusion Matrix: 
[[835 358]
 [ 74 554]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:12<00:00, 57.25it/s, loss=0.258]


Loss: 1.09280017410454
Accuracy: 0.7677100494233937
F1: 0.7428571428571429
Confusion Matrix: 
[[787 301]
 [122 611]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:12<00:00, 57.01it/s, loss=0.00393]


Loss: 0.9133059466094301
Accuracy: 0.8039538714991763
F1: 0.8013355592654424
Confusion Matrix: 
[[744 192]
 [165 720]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:12<00:00, 57.39it/s, loss=0.00208]


Loss: 1.0524642876627153
Accuracy: 0.8193300384404174
F1: 0.8249068653539117
Confusion Matrix: 
[[717 137]
 [192 775]]
Loss: 1.0524642876627153
Accuracy: 0.8193300384404174
F1: 0.8249068653539117
Confusion Matrix: 
[[717 137]
 [192 775]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:11<00:00, 60.90it/s, loss=0.109]


Loss: 1.1307651886814518
Accuracy: 0.814936847885777
F1: 0.8068767908309455
Confusion Matrix: 
[[780 208]
 [129 704]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:10<00:00, 65.01it/s, loss=0.000422]


Loss: 1.5551531819397943
Accuracy: 0.7742998352553542
F1: 0.7367072389493914
Confusion Matrix: 
[[835 337]
 [ 74 575]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:10<00:00, 63.03it/s, loss=0.213]


Loss: 0.9997192579403258
Accuracy: 0.8077979132344866
F1: 0.8015873015873016
Confusion Matrix: 
[[764 205]
 [145 707]]
Loss: 0.9997192579403258
Accuracy: 0.8077979132344866
F1: 0.8015873015873016
Confusion Matrix: 
[[764 205]
 [145 707]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:11<00:00, 61.81it/s, loss=0.579]


Loss: 1.127720053520119
Accuracy: 0.7995606809445359
F1: 0.779189352692075
Confusion Matrix: 
[[812 268]
 [ 97 644]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:11<00:00, 60.99it/s, loss=0.000569]


Loss: 1.344134804972431
Accuracy: 0.7896760021965953
F1: 0.7643076923076924
Confusion Matrix: 
[[817 291]
 [ 92 621]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:11<00:00, 60.91it/s, loss=0.000197]


Loss: 1.5392877629451585
Accuracy: 0.7874794069192751
F1: 0.7661631419939577
Confusion Matrix: 
[[800 278]
 [109 634]]
Loss: 1.5392877629451585
Accuracy: 0.7874794069192751
F1: 0.7661631419939577
Confusion Matrix: 
[[800 278]
 [109 634]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 87.59it/s, loss=0.000369]


Loss: 1.2926677240614306
Accuracy: 0.7962657880285557
F1: 0.7876359473382942
Confusion Matrix: 
[[762 224]
 [147 688]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 89.90it/s, loss=0.000538]


Loss: 1.2536012344715888
Accuracy: 0.7995606809445359
F1: 0.7927314026121521
Confusion Matrix: 
[[758 214]
 [151 698]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 83.57it/s, loss=0.00205]


Loss: 1.2008892334344095
Accuracy: 0.7946183415705657
F1: 0.7919911012235817
Confusion Matrix: 
[[735 200]
 [174 712]]
Loss: 1.2008892334344095
Accuracy: 0.7946183415705657
F1: 0.7919911012235817
Confusion Matrix: 
[[735 200]
 [174 712]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:07<00:00, 91.96it/s, loss=0.776]


Loss: 1.1416419690246122
Accuracy: 0.800658978583196
F1: 0.7917383820998278
Confusion Matrix: 
[[768 222]
 [141 690]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 83.96it/s, loss=0.000768]


Loss: 1.4032989732528989
Accuracy: 0.7924217462932455
F1: 0.7789473684210526
Confusion Matrix: 
[[777 246]
 [132 666]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 86.29it/s, loss=0.000385]


Loss: 1.5061054616643672
Accuracy: 0.7699066447007139
F1: 0.7405572755417956
Confusion Matrix: 
[[804 314]
 [105 598]]
Loss: 1.5061054616643672
Accuracy: 0.7699066447007139
F1: 0.7405572755417956
Confusion Matrix: 
[[804 314]
 [105 598]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:25<00:00, 26.80it/s, loss=0.000439]


Loss: 1.4966026931478267
Accuracy: 0.7995606809445359
F1: 0.7891392258809936
Confusion Matrix: 
[[773 229]
 [136 683]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:25<00:00, 26.65it/s, loss=0.000402]


Loss: 1.4657008725671883
Accuracy: 0.800658978583196
F1: 0.7858407079646018
Confusion Matrix: 
[[792 246]
 [117 666]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:25<00:00, 26.70it/s, loss=0.000189]


Loss: 1.7736348504560036
Accuracy: 0.7907742998352554
F1: 0.7658266748617086
Confusion Matrix: 
[[817 289]
 [ 92 623]]
Loss: 1.7736348504560036
Accuracy: 0.7907742998352554
F1: 0.7658266748617086
Confusion Matrix: 
[[817 289]
 [ 92 623]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:26<00:00, 26.56it/s, loss=0.000664]


Loss: 1.3945913831177454
Accuracy: 0.7935200439319056
F1: 0.8129353233830846
Confusion Matrix: 
[[628  95]
 [281 817]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:26<00:00, 26.61it/s, loss=0.000303]


Loss: 1.5859284434812715
Accuracy: 0.7885777045579352
F1: 0.8050632911392405
Confusion Matrix: 
[[641 117]
 [268 795]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:25<00:00, 26.62it/s, loss=0.000498]


Loss: 1.3605954456224776
Accuracy: 0.8094453596924767
F1: 0.8168865435356201
Confusion Matrix: 
[[700 138]
 [209 774]]
Loss: 1.3605954456224776
Accuracy: 0.8094453596924767
F1: 0.8168865435356201
Confusion Matrix: 
[[700 138]
 [209 774]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:15<00:00, 44.81it/s, loss=0.000558]


Loss: 1.4181640642253976
Accuracy: 0.7924217462932455
F1: 0.8081218274111676
Confusion Matrix: 
[[647 116]
 [262 796]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:15<00:00, 44.73it/s, loss=0.000385]


Loss: 1.4388527221846998
Accuracy: 0.7968149368478857
F1: 0.8110316649642493
Confusion Matrix: 
[[657 118]
 [252 794]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:15<00:00, 44.71it/s, loss=0.000271]


Loss: 1.4270016151039224
Accuracy: 0.7946183415705657
F1: 0.7879818594104309
Confusion Matrix: 
[[752 217]
 [157 695]]
Loss: 1.4270016151039224
Accuracy: 0.7946183415705657
F1: 0.7879818594104309
Confusion Matrix: 
[[752 217]
 [157 695]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:15<00:00, 43.68it/s, loss=0.000387]


Loss: 1.3635522754568803
Accuracy: 0.8017572762218561
F1: 0.8056004308023694
Confusion Matrix: 
[[712 164]
 [197 748]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:15<00:00, 44.81it/s, loss=0.000303]


Loss: 1.6660230902203343
Accuracy: 0.7803404722679846
F1: 0.7536945812807881
Confusion Matrix: 
[[809 300]
 [100 612]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:15<00:00, 44.68it/s, loss=0.000304]


Loss: 1.5973374623511183
Accuracy: 0.7946183415705657
F1: 0.7812865497076024
Confusion Matrix: 
[[779 244]
 [130 668]]
Loss: 1.5973374623511183
Accuracy: 0.7946183415705657
F1: 0.7812865497076024
Confusion Matrix: 
[[779 244]
 [130 668]]
Testing model
Loss: 1.750489882592644
Accuracy: 0.7752293577981652
F1: 0.755
Confusion Matrix: 
[[374 126]
 [ 70 302]]

 Grid search finished.
Best F1-score: 0.8249
Best hyperparameters: {'model_type': 'GRU', 'hidden_size': 150, 'num_layers': 10, 'dropout': 0.25, 'bidirectional': False}


In [ ]:
def grid_search(args):
  seed = args.seed

  model_type = ['RNN']
  hidden_size = [150, 300]
  num_layers = [3, 10]
  bidirectional = [True, False]
  dropout = [0.05, 0.25]
  best_f1 = 0
  best_model_state = None
  best_params = None

  train_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_train_raw.csv')
  valid_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_valid_raw.csv')
  test_dataset = NPLDataset('/content/drive/MyDrive/Colab Notebooks/sst_test_raw.csv')
  vocab = train_dataset.text_vocab
  valid_dataset.text_vocab = vocab
  test_dataset.text_vocab = vocab
  valid_dataset.label_vocab = train_dataset.label_vocab
  test_dataset.label_vocab = train_dataset.label_vocab

  train_dataloader = DataLoader(dataset=train_dataset, batch_size=args.batch_size, shuffle=True, collate_fn=pad_collate_fn)
  valid_dataloader = DataLoader(dataset=valid_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)
  test_dataloader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=False, collate_fn=pad_collate_fn)

  embedding = Embedding(vocab, '/content/drive/MyDrive/Colab Notebooks/sst_glove_6b_300d.txt', args.embedding_dim)
  np.random.seed(seed)
  torch.manual_seed(seed)

  for type_ in model_type:
    print(f"Model type: {type_}")
    for hs, nl, bi, dp in itertools.product(hidden_size, num_layers, bidirectional, dropout):
      model = RNN(type_, embedding=embedding, input_size=args.embedding_dim, hidden_size=hs, num_layers=nl, bidirectional=bi, dropout=dp)
      model.to(args.device)

      criterion = nn.BCEWithLogitsLoss()
      optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

      for epoch in range(args.epochs):
        print(f"Epoch: {epoch+1}")
        train(model, train_dataloader, optimizer, criterion, args)
        evaluate(model, valid_dataloader, criterion, args)

      val_loss, val_acc, val_f1, val_cm = evaluate(model, valid_dataloader, criterion, args)

      if val_f1 > best_f1:
            best_f1 = val_f1
            best_model_state = model.state_dict()
            best_params = {
                'model_type': type_,
                'hidden_size': hs,
                'num_layers': nl,
                'dropout': dp,
                'bidirectional': bi
            }
            torch.save({'model_state_dict': best_model_state, 'params': best_params}, 'best_params_RNN.pt')

    print("Testing model")
    evaluate(model, test_dataloader, criterion, args)

  print("\n Grid search finished.")
  print(f"Best F1-score: {best_f1:.4f}")
  print(f"Best hyperparameters: {best_params}")

In [ ]:
args = {
    "seed": 7052020,
    "batch_size": 10,
    "embedding_dim": 300,
    "epochs": 3,
    "device": torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
    "clip": 0.25
}

grid_search(SimpleNamespace(**args))

<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)
<ipython-input-6-c9cb7466cede>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  csv = pd.read_csv(path, sep=', ', header=None)


Model type: RNN
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 111.74it/s, loss=0.471]


Loss: 0.6955765459621162
Accuracy: 0.6326194398682042
F1: 0.49356548069644207
Confusion Matrix: 
[[826 586]
 [ 83 326]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 131.45it/s, loss=0.366]


Loss: 0.7693290012447458
Accuracy: 0.6781987918725975
F1: 0.6008174386920981
Confusion Matrix: 
[[794 471]
 [115 441]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:05<00:00, 116.62it/s, loss=0.304]


Loss: 0.8804093957470175
Accuracy: 0.6457990115321252
F1: 0.48109412711182625
Confusion Matrix: 
[[877 613]
 [ 32 299]]
Loss: 0.8804093957470175
Accuracy: 0.6457990115321252
F1: 0.48109412711182625
Confusion Matrix: 
[[877 613]
 [ 32 299]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:05<00:00, 129.16it/s, loss=0.733]


Loss: 0.695558067999388
Accuracy: 0.49917627677100496
F1: 0.02145922746781116
Confusion Matrix: 
[[899 902]
 [ 10  10]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 126.66it/s, loss=0.364]


Loss: 0.5605477319474805
Accuracy: 0.7688083470620538
F1: 0.7545189504373178
Confusion Matrix: 
[[753 265]
 [156 647]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:05<00:00, 119.21it/s, loss=0.334]


Loss: 0.7087854928614801
Accuracy: 0.7528830313014827
F1: 0.716624685138539
Confusion Matrix: 
[[802 343]
 [107 569]]
Loss: 0.7087854928614801
Accuracy: 0.7528830313014827
F1: 0.716624685138539
Confusion Matrix: 
[[802 343]
 [107 569]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:04<00:00, 142.46it/s, loss=0.3]


Loss: 0.5990048280933447
Accuracy: 0.7660626029654036
F1: 0.73992673992674
Confusion Matrix: 
[[789 306]
 [120 606]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 130.11it/s, loss=0.321]


Loss: 0.6672578166451371
Accuracy: 0.7660626029654036
F1: 0.7464285714285714
Confusion Matrix: 
[[768 285]
 [141 627]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 143.05it/s, loss=0.715]


Loss: 0.8870250360484708
Accuracy: 0.7243272926963207
F1: 0.6598915989159891
Confusion Matrix: 
[[832 425]
 [ 77 487]]
Loss: 0.8870250360484708
Accuracy: 0.7243272926963207
F1: 0.6598915989159891
Confusion Matrix: 
[[832 425]
 [ 77 487]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:04<00:00, 139.51it/s, loss=0.173]


Loss: 0.5513349008141902
Accuracy: 0.7677100494233937
F1: 0.7777193904361535
Confusion Matrix: 
[[658 172]
 [251 740]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:05<00:00, 128.41it/s, loss=0.381]


Loss: 0.6038747474289777
Accuracy: 0.7929708951125755
F1: 0.7927432655305112
Confusion Matrix: 
[[723 191]
 [186 721]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:04<00:00, 142.42it/s, loss=0.9]


Loss: 0.955682574003412
Accuracy: 0.7721032399780341
F1: 0.7439851943244911
Confusion Matrix: 
[[803 309]
 [106 603]]
Loss: 0.955682574003412
Accuracy: 0.7721032399780341
F1: 0.7439851943244911
Confusion Matrix: 
[[803 309]
 [106 603]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 78.35it/s, loss=0.693]


Loss: 0.6965815885025158
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 84.60it/s, loss=0.0728]


Loss: 0.6529649077800282
Accuracy: 0.7693574958813838
F1: 0.7648376259798432
Confusion Matrix: 
[[718 229]
 [191 683]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 81.65it/s, loss=0.362]


Loss: 1.1004488777957464
Accuracy: 0.7358594179022515
F1: 0.6773977196512407
Confusion Matrix: 
[[835 407]
 [ 74 505]]
Loss: 1.1004488777957464
Accuracy: 0.7358594179022515
F1: 0.6773977196512407
Confusion Matrix: 
[[835 407]
 [ 74 505]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 77.53it/s, loss=0.642]


Loss: 0.7027843521352399
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:08<00:00, 86.17it/s, loss=0.694]


Loss: 0.6971098215956437
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 80.16it/s, loss=0.699]


Loss: 0.6932266344103897
Accuracy: 0.500823723228995
F1: 0.6673984632272228
Confusion Matrix: 
[[  0   0]
 [909 912]]
Loss: 0.6932266344103897
Accuracy: 0.500823723228995
F1: 0.6673984632272228
Confusion Matrix: 
[[  0   0]
 [909 912]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 102.36it/s, loss=0.527]


Loss: 0.5363412980447736
Accuracy: 0.8045030203185063
F1: 0.8033149171270718
Confusion Matrix: 
[[738 185]
 [171 727]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 114.77it/s, loss=0.427]


Loss: 0.923008128608528
Accuracy: 0.7556287753981329
F1: 0.7100977198697068
Confusion Matrix: 
[[831 367]
 [ 78 545]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 104.31it/s, loss=0.0149]


Loss: 0.9137086583334103
Accuracy: 0.7781438769906645
F1: 0.7551515151515151
Confusion Matrix: 
[[794 289]
 [115 623]]
Loss: 0.9137086583334103
Accuracy: 0.7781438769906645
F1: 0.7551515151515151
Confusion Matrix: 
[[794 289]
 [115 623]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 112.53it/s, loss=0.381]


Loss: 0.8236229307295984
Accuracy: 0.7171883580450302
F1: 0.6370683579985905
Confusion Matrix: 
[[854 460]
 [ 55 452]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 105.71it/s, loss=0.438]


Loss: 1.2423783945932723
Accuracy: 0.7127951674903898
F1: 0.6329824561403509
Confusion Matrix: 
[[847 461]
 [ 62 451]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 110.04it/s, loss=0.0157]


Loss: 1.0547837902579391
Accuracy: 0.7600219659527732
F1: 0.7406528189910979
Confusion Matrix: 
[[760 288]
 [149 624]]
Loss: 1.0547837902579391
Accuracy: 0.7600219659527732
F1: 0.7406528189910979
Confusion Matrix: 
[[760 288]
 [149 624]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 79.85it/s, loss=0.18]


Loss: 0.7448394245615131
Accuracy: 0.800658978583196
F1: 0.7868467410452143
Confusion Matrix: 
[[788 242]
 [121 670]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 88.54it/s, loss=1.29]


Loss: 1.6232987302437163
Accuracy: 0.728171334431631
F1: 0.647184604419102
Confusion Matrix: 
[[872 458]
 [ 37 454]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 80.69it/s, loss=0.657]


Loss: 1.2732380165865547
Accuracy: 0.7759472817133443
F1: 0.7487684729064039
Confusion Matrix: 
[[805 304]
 [104 608]]
Loss: 1.2732380165865547
Accuracy: 0.7759472817133443
F1: 0.7487684729064039
Confusion Matrix: 
[[805 304]
 [104 608]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:08<00:00, 80.63it/s, loss=0.00279]


Loss: 1.4483596081273598
Accuracy: 0.7484898407468424
F1: 0.7183271832718328
Confusion Matrix: 
[[779 328]
 [130 584]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:07<00:00, 87.20it/s, loss=0.951]


Loss: 1.279570237063525
Accuracy: 0.7473915431081823
F1: 0.7012987012987013
Confusion Matrix: 
[[821 372]
 [ 88 540]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:08<00:00, 83.75it/s, loss=0.00209]


Loss: 1.627450067484588
Accuracy: 0.7331136738056013
F1: 0.6785714285714286
Confusion Matrix: 
[[822 399]
 [ 87 513]]
Loss: 1.627450067484588
Accuracy: 0.7331136738056013
F1: 0.6785714285714286
Confusion Matrix: 
[[822 399]
 [ 87 513]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 100.50it/s, loss=0.00279]


Loss: 1.446896719043715
Accuracy: 0.7561779242174629
F1: 0.7157490396927016
Confusion Matrix: 
[[818 353]
 [ 91 559]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 112.11it/s, loss=0.00785]


Loss: 1.2867480539961864
Accuracy: 0.7457440966501923
F1: 0.6991552956465237
Confusion Matrix: 
[[820 374]
 [ 89 538]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 101.81it/s, loss=0.00414]


Loss: 1.7586738778310909
Accuracy: 0.7045579352004393
F1: 0.6020710059171598
Confusion Matrix: 
[[876 505]
 [ 33 407]]
Loss: 1.7586738778310909
Accuracy: 0.7045579352004393
F1: 0.6020710059171598
Confusion Matrix: 
[[876 505]
 [ 33 407]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:06<00:00, 112.26it/s, loss=0.00301]


Loss: 1.566548162646461
Accuracy: 0.7105985722130698
F1: 0.6167272727272727
Confusion Matrix: 
[[870 488]
 [ 39 424]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:06<00:00, 101.43it/s, loss=0.00348]


Loss: 1.3929360153382284
Accuracy: 0.7336628226249313
F1: 0.6751507032819826
Confusion Matrix: 
[[832 408]
 [ 77 504]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:06<00:00, 112.64it/s, loss=0.548]


Loss: 1.5284232993920643
Accuracy: 0.7550796265788029
F1: 0.7306763285024155
Confusion Matrix: 
[[770 307]
 [139 605]]
Loss: 1.5284232993920643
Accuracy: 0.7550796265788029
F1: 0.7306763285024155
Confusion Matrix: 
[[770 307]
 [139 605]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:18<00:00, 37.69it/s, loss=0.675]


Loss: 0.6623571311172686
Accuracy: 0.6243822075782537
F1: 0.4722222222222222
Confusion Matrix: 
[[831 606]
 [ 78 306]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:17<00:00, 39.35it/s, loss=0.877]


Loss: 0.7291479345999266
Accuracy: 0.528281164195497
F1: 0.6742510428517254
Confusion Matrix: 
[[ 73  23]
 [836 889]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:18<00:00, 37.61it/s, loss=0.684]


Loss: 0.6938563428427044
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Loss: 0.6938563428427044
Accuracy: 0.49917627677100496
F1: 0.0
Confusion Matrix: 
[[909 912]
 [  0   0]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:17<00:00, 39.19it/s, loss=0.601]


Loss: 0.6666816755344993
Accuracy: 0.5919824272377814
F1: 0.35559410234171723
Confusion Matrix: 
[[873 707]
 [ 36 205]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:18<00:00, 37.85it/s, loss=0.642]


Loss: 0.7184463990362067
Accuracy: 0.5475013728720484
F1: 0.21523809523809523
Confusion Matrix: 
[[884 799]
 [ 25 113]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:17<00:00, 39.48it/s, loss=0.726]


Loss: 0.7092297641854537
Accuracy: 0.5436573311367381
F1: 0.1844946025515211
Confusion Matrix: 
[[896 818]
 [ 13  94]]
Loss: 0.7092297641854537
Accuracy: 0.5436573311367381
F1: 0.1844946025515211
Confusion Matrix: 
[[896 818]
 [ 13  94]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:10<00:00, 66.66it/s, loss=0.77]


Loss: 0.9312525971939689
Accuracy: 0.7995606809445359
F1: 0.8002189381499726
Confusion Matrix: 
[[725 181]
 [184 731]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:10<00:00, 64.13it/s, loss=0.623]


Loss: 1.2075879241813694
Accuracy: 0.7836353651839648
F1: 0.7609223300970874
Confusion Matrix: 
[[800 285]
 [109 627]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:11<00:00, 62.75it/s, loss=0.00147]


Loss: 1.3700821376160572
Accuracy: 0.7770455793520044
F1: 0.7518337408312958
Confusion Matrix: 
[[800 297]
 [109 615]]
Loss: 1.3700821376160572
Accuracy: 0.7770455793520044
F1: 0.7518337408312958
Confusion Matrix: 
[[800 297]
 [109 615]]
Epoch: 1


Training: 100%|██████████| 692/692 [00:11<00:00, 62.71it/s, loss=0.00703]


Loss: 1.0163533337283552
Accuracy: 0.7973640856672158
F1: 0.7955678670360111
Confusion Matrix: 
[[734 194]
 [175 718]]
Epoch: 2


Training: 100%|██████████| 692/692 [00:11<00:00, 62.69it/s, loss=0.00258]


Loss: 1.1209812446644432
Accuracy: 0.800109829763866
F1: 0.8010928961748633
Confusion Matrix: 
[[724 179]
 [185 733]]
Epoch: 3


Training: 100%|██████████| 692/692 [00:11<00:00, 62.62it/s, loss=0.725]


Loss: 1.9332673889503145
Accuracy: 0.728171334431631
F1: 0.6555323590814196
Confusion Matrix: 
[[855 441]
 [ 54 471]]
Loss: 1.9332673889503145
Accuracy: 0.728171334431631
F1: 0.6555323590814196
Confusion Matrix: 
[[855 441]
 [ 54 471]]
Testing model
Loss: 1.8775914467197643
Accuracy: 0.7362385321100917
F1: 0.6685878962536023
Confusion Matrix: 
[[410 196]
 [ 34 232]]

 Grid search finished.
Best F1-score: 0.7552
Best hyperparameters: {'model_type': 'RNN', 'hidden_size': 150, 'num_layers': 10, 'dropout': 0.05, 'bidirectional': False}
